import type { Metadata } from "next";
import "../globals.css";
import { Tabs } from "./[id]/_components/Tabs";

export const metadata: Metadata = {
  title: "Football App",
  description: "Generated by create next app",
};

export default async function RootLayout({children,}: Readonly<{children: React.ReactNode;}>) {
  
  return (
    <>
      <div className="max-w-[800px] mx-auto">
        <Tabs />
        {children}
      </div>
    </>
  );
}
