import type { Metadata } from "next";
import "./globals.css";
import { Header } from "@/app/_components/Header";

export const metadata: Metadata = {
  title: "Football App",
  description: "Generated by create next app",
};

export default async function RootLayout({children,}: Readonly<{children: React.ReactNode;}>) {
  
  return (
    <html lang="ja">
      <body className={`antialiased`}>
        <Header />
        <div className="py-[100px] max-md:w-[96%] max-md:mx-auto">
          {children}
        </div>
      </body>
    </html>
  );
}
